/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTargetRouteImport } from './routes/_authenticated/target'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPlayersRouteImport } from './routes/_authenticated/players'
import { Route as AuthenticatedMenuRouteImport } from './routes/_authenticated/menu'
import { Route as AuthenticatedMapRouteImport } from './routes/_authenticated/map'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedFeedRouteImport } from './routes/_authenticated/feed'
import { Route as AuthenticatedClipsRouteImport } from './routes/_authenticated/clips'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedSettingsGameIdRouteImport } from './routes/_authenticated/settings.$gameId'
import { Route as AuthenticatedPlayersGameIdRouteImport } from './routes/_authenticated/players.$gameId'
import { Route as AuthenticatedGameGameIdRouteImport } from './routes/_authenticated/game.$gameId'
import { Route as AuthenticatedClipsNewRouteImport } from './routes/_authenticated/clips_.new'
import { Route as AuthenticatedAdminGameIdRouteImport } from './routes/_authenticated/admin.$gameId'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTargetRoute = AuthenticatedTargetRouteImport.update({
  id: '/target',
  path: '/target',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlayersRoute = AuthenticatedPlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMenuRoute = AuthenticatedMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMapRoute = AuthenticatedMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFeedRoute = AuthenticatedFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClipsRoute = AuthenticatedClipsRouteImport.update({
  id: '/clips',
  path: '/clips',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsGameIdRoute =
  AuthenticatedSettingsGameIdRouteImport.update({
    id: '/settings/$gameId',
    path: '/settings/$gameId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlayersGameIdRoute =
  AuthenticatedPlayersGameIdRouteImport.update({
    id: '/$gameId',
    path: '/$gameId',
    getParentRoute: () => AuthenticatedPlayersRoute,
  } as any)
const AuthenticatedGameGameIdRoute = AuthenticatedGameGameIdRouteImport.update({
  id: '/game/$gameId',
  path: '/game/$gameId',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClipsNewRoute = AuthenticatedClipsNewRouteImport.update({
  id: '/clips_/new',
  path: '/clips/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminGameIdRoute =
  AuthenticatedAdminGameIdRouteImport.update({
    id: '/admin/$gameId',
    path: '/admin/$gameId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/chat': typeof AuthenticatedChatRoute
  '/clips': typeof AuthenticatedClipsRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/home': typeof AuthenticatedHomeRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/map': typeof AuthenticatedMapRoute
  '/menu': typeof AuthenticatedMenuRoute
  '/players': typeof AuthenticatedPlayersRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/target': typeof AuthenticatedTargetRoute
  '/admin/$gameId': typeof AuthenticatedAdminGameIdRoute
  '/clips/new': typeof AuthenticatedClipsNewRoute
  '/game/$gameId': typeof AuthenticatedGameGameIdRoute
  '/players/$gameId': typeof AuthenticatedPlayersGameIdRoute
  '/settings/$gameId': typeof AuthenticatedSettingsGameIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/chat': typeof AuthenticatedChatRoute
  '/clips': typeof AuthenticatedClipsRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/home': typeof AuthenticatedHomeRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/map': typeof AuthenticatedMapRoute
  '/menu': typeof AuthenticatedMenuRoute
  '/players': typeof AuthenticatedPlayersRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/target': typeof AuthenticatedTargetRoute
  '/admin/$gameId': typeof AuthenticatedAdminGameIdRoute
  '/clips/new': typeof AuthenticatedClipsNewRoute
  '/game/$gameId': typeof AuthenticatedGameGameIdRoute
  '/players/$gameId': typeof AuthenticatedPlayersGameIdRoute
  '/settings/$gameId': typeof AuthenticatedSettingsGameIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/clips': typeof AuthenticatedClipsRoute
  '/_authenticated/feed': typeof AuthenticatedFeedRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/map': typeof AuthenticatedMapRoute
  '/_authenticated/menu': typeof AuthenticatedMenuRoute
  '/_authenticated/players': typeof AuthenticatedPlayersRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/target': typeof AuthenticatedTargetRoute
  '/_authenticated/admin/$gameId': typeof AuthenticatedAdminGameIdRoute
  '/_authenticated/clips_/new': typeof AuthenticatedClipsNewRoute
  '/_authenticated/game/$gameId': typeof AuthenticatedGameGameIdRoute
  '/_authenticated/players/$gameId': typeof AuthenticatedPlayersGameIdRoute
  '/_authenticated/settings/$gameId': typeof AuthenticatedSettingsGameIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/chat'
    | '/clips'
    | '/feed'
    | '/home'
    | '/leaderboard'
    | '/map'
    | '/menu'
    | '/players'
    | '/profile'
    | '/target'
    | '/admin/$gameId'
    | '/clips/new'
    | '/game/$gameId'
    | '/players/$gameId'
    | '/settings/$gameId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/chat'
    | '/clips'
    | '/feed'
    | '/home'
    | '/leaderboard'
    | '/map'
    | '/menu'
    | '/players'
    | '/profile'
    | '/target'
    | '/admin/$gameId'
    | '/clips/new'
    | '/game/$gameId'
    | '/players/$gameId'
    | '/settings/$gameId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/onboarding'
    | '/_authenticated/chat'
    | '/_authenticated/clips'
    | '/_authenticated/feed'
    | '/_authenticated/home'
    | '/_authenticated/leaderboard'
    | '/_authenticated/map'
    | '/_authenticated/menu'
    | '/_authenticated/players'
    | '/_authenticated/profile'
    | '/_authenticated/target'
    | '/_authenticated/admin/$gameId'
    | '/_authenticated/clips_/new'
    | '/_authenticated/game/$gameId'
    | '/_authenticated/players/$gameId'
    | '/_authenticated/settings/$gameId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/target': {
      id: '/_authenticated/target'
      path: '/target'
      fullPath: '/target'
      preLoaderRoute: typeof AuthenticatedTargetRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/players': {
      id: '/_authenticated/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof AuthenticatedPlayersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/menu': {
      id: '/_authenticated/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof AuthenticatedMenuRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/map': {
      id: '/_authenticated/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AuthenticatedMapRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/feed': {
      id: '/_authenticated/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedFeedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clips': {
      id: '/_authenticated/clips'
      path: '/clips'
      fullPath: '/clips'
      preLoaderRoute: typeof AuthenticatedClipsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/$gameId': {
      id: '/_authenticated/settings/$gameId'
      path: '/settings/$gameId'
      fullPath: '/settings/$gameId'
      preLoaderRoute: typeof AuthenticatedSettingsGameIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/players/$gameId': {
      id: '/_authenticated/players/$gameId'
      path: '/$gameId'
      fullPath: '/players/$gameId'
      preLoaderRoute: typeof AuthenticatedPlayersGameIdRouteImport
      parentRoute: typeof AuthenticatedPlayersRoute
    }
    '/_authenticated/game/$gameId': {
      id: '/_authenticated/game/$gameId'
      path: '/game/$gameId'
      fullPath: '/game/$gameId'
      preLoaderRoute: typeof AuthenticatedGameGameIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clips_/new': {
      id: '/_authenticated/clips_/new'
      path: '/clips/new'
      fullPath: '/clips/new'
      preLoaderRoute: typeof AuthenticatedClipsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/$gameId': {
      id: '/_authenticated/admin/$gameId'
      path: '/admin/$gameId'
      fullPath: '/admin/$gameId'
      preLoaderRoute: typeof AuthenticatedAdminGameIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedPlayersRouteChildren {
  AuthenticatedPlayersGameIdRoute: typeof AuthenticatedPlayersGameIdRoute
}

const AuthenticatedPlayersRouteChildren: AuthenticatedPlayersRouteChildren = {
  AuthenticatedPlayersGameIdRoute: AuthenticatedPlayersGameIdRoute,
}

const AuthenticatedPlayersRouteWithChildren =
  AuthenticatedPlayersRoute._addFileChildren(AuthenticatedPlayersRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedClipsRoute: typeof AuthenticatedClipsRoute
  AuthenticatedFeedRoute: typeof AuthenticatedFeedRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedMapRoute: typeof AuthenticatedMapRoute
  AuthenticatedMenuRoute: typeof AuthenticatedMenuRoute
  AuthenticatedPlayersRoute: typeof AuthenticatedPlayersRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedTargetRoute: typeof AuthenticatedTargetRoute
  AuthenticatedAdminGameIdRoute: typeof AuthenticatedAdminGameIdRoute
  AuthenticatedClipsNewRoute: typeof AuthenticatedClipsNewRoute
  AuthenticatedGameGameIdRoute: typeof AuthenticatedGameGameIdRoute
  AuthenticatedSettingsGameIdRoute: typeof AuthenticatedSettingsGameIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedClipsRoute: AuthenticatedClipsRoute,
  AuthenticatedFeedRoute: AuthenticatedFeedRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedMapRoute: AuthenticatedMapRoute,
  AuthenticatedMenuRoute: AuthenticatedMenuRoute,
  AuthenticatedPlayersRoute: AuthenticatedPlayersRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedTargetRoute: AuthenticatedTargetRoute,
  AuthenticatedAdminGameIdRoute: AuthenticatedAdminGameIdRoute,
  AuthenticatedClipsNewRoute: AuthenticatedClipsNewRoute,
  AuthenticatedGameGameIdRoute: AuthenticatedGameGameIdRoute,
  AuthenticatedSettingsGameIdRoute: AuthenticatedSettingsGameIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
